# Generated by Django 4.2.8 on 2025-05-11 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0052_remove_rasterstyle_rendering_engine"),
        ("geomanager", "0054_remove_dataset_initial_date_and_more"),
    ]

    operations = []
