# Generated by Django 5.2.7 on 2025-10-04 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geomanager", "0056_alter_dataset_latest_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rasterfilelayer",
            options={
                "ordering": ["created"],
                "verbose_name": "Raster File Layer",
                "verbose_name_plural": "Raster File Layers",
            },
        ),
        migrations.AlterModelOptions(
            name="wmslayer",
            options={"ordering": ["created"], "verbose_name": "WMS Layer", "verbose_name_plural": "WMS Layers"},
        ),
    ]
